name: 'action-update-dprint-plugins'
description: 'Update dprint plugins in dprint.json config file'
author: 'Kenichi Kamiya <kachick1@gmail.com>'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  base-branch:
    description: 'The branch into which you want updating PR merged'
    required: true
  github-token:
    description: 'The token will be used to create PR'
    required: true
  # auto-merge:
  #   description: 'The updating PR will be auto merged if no change exist even after `dprint fmt`'
  #   required: false
  #   default: 'true'
outputs:
  pr_url:
    description: 'Created PR URL'
    value: ${{ steps.pr.outputs.pr_url  }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - id: setup
      run: |
        timestamp=`date +"%Y%m%d-%H%M-UTC"`
        echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT
        echo "branch=action-update-dprint-plugins-${timestamp}" >> $GITHUB_OUTPUT
      shell: bash
    - name: git setting
      run: |
        git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
      shell: bash
    # Referenced https://github.com/dprint/check/blob/2f1cf31537886c3bfb05591c031f7744e48ba8a1/action.yml#L16-L20
    - name: Install dprint
      shell: bash
      run: |
        curl -fsSL https://dprint.dev/install.sh | sh -s > /dev/null 2>&1
        echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
    - name: Create branch
      run: |
        git switch -c "${{ steps.setup.outputs.branch }}"
      shell: bash
    - id: update_plugins
      run: |
        ~/.dprint/bin/dprint config update --yes
        if git add --intent-to-add . && git diff --exit-code; then
          echo 'update=false' >> $GITHUB_OUTPUT
        else
          echo 'update=true' >> $GITHUB_OUTPUT
          git commit -a -m 'chore: `dprint config update`'
        fi
      shell: bash
    - id: fmt
      if: ${{ steps.update_plugins.outputs.update == 'true' }}
      run: |
        ~/.dprint/bin/dprint fmt
        if git add --intent-to-add . && git diff --exit-code; then
          echo 'fmt=false' >> $GITHUB_OUTPUT
        else
          echo 'fmt=true' >> $GITHUB_OUTPUT
          git commit -a -m 'chore: `dprint fmt`'
        fi
      shell: bash
    - id: pr
      if: ${{ steps.update_plugins.outputs.update == 'true' || steps.fmt.outputs.fmt == 'true' }}
      run: |
        git push -u origin "${{ steps.setup.outputs.branch }}"
        echo "pr_url=$(gh pr create --fill --base ${{ inputs.base-branch}} --title 'Update dprint plugins' --body 'This PR has been created by https://github.com/kachick/action-update-dprint-plugins')" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: '${{ inputs.github-token }}'
      shell: bash
    # - name: Auto merge
    #   if: ${{ inputs.auto-merge == 'true' && steps.update_plugins.outputs.update == 'true' && steps.fmt.outputs.fmt == 'false' }}
    #   run: gh pr merge --auto --squash "${{ steps.pr.outputs.pr_url }}"
    #   shell: bash
    #   env:
    #     GITHUB_TOKEN: '${{ inputs.github-token }}'
