name: Update
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/dprint.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  schedule:
    # Run at 17:00 UTC every Monday
    - cron: '0 17 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: 'update-dprint'
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          base-branch: 'main'
          # Keep same version as used in *.nix
          dprint-version: '0.39.1'
          fmt: false
